
format = "$username$hostname$all$directory$git_branch$git_status$cmd_duration$sudo$shell$time[\nğŸ’€\n]()$status$character"

## FIRST LINE/ROW: Info & Status
# First param â”€â”Œ
[username]
format = " [â•­â”€ $user]($style)ğŸª"
style_user = "bold yellow"
style_root = "bold yellow"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bold yellow"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
format = "in [$path]($style)[$read_only]($read_only_style)"
style = "bold green"
read_only = " ğŸ”"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = " took [$duration](bold red) [â”€](bold yellow)"
show_notifications = true
min_time_to_notify = 300000
disabled = false

[fill]
symbol = 'â”€'
style = 'bold yellow'

## SECOND LINE/ROW: Prompt
# Somethere at the beginning

# Prompt: optional param 1
[time]
format = " at âŒš [$time](bold red)[ â”€â¯](bold yellow)"
time_format = "%T"
disabled = true

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€â¯](bold yellow)"
error_symbol = "[â”€â¯](bold yellow)"

# SYMBOLS
[status]
symbol = "ğŸ”´"
format = '[ [â•°â”€](bold yellow)\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
symbol = 'ğŸ…° '

[azure]
symbol = 'ï´ƒ '

[bun]
symbol = 'ğŸ '

[c]
symbol = 'ğŸ‡¨  '

[docker_context]
symbol = "ğŸ‹ "

[git_branch]
format = ' on [$symbol$branch(:$remote_branch)]($style) '
symbol = "ğŸŒ± "

[golang]
symbol = "ğŸ¹ "

[java]
symbol = "â˜• "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ğŸ“¦ "

[python]
symbol = "ğŸ "

[rust]
symbol = "ğŸ¦€ "

[shell]
format = " on [$indicator â”€â¯]($style)"
bash_indicator = "ğŸ§"
fish_indicator = "ğŸ "
zsh_indicator = "ğŸ¦“"
unknown_indicator = 'ğŸ‘½'
style = "bold yellow"
disabled = false

[sudo]
format = " as [$symbol]($style)"
symbol = "ğŸ§™"
disabled = false

[line_break]
disabled = true

